# Generated by Django 4.1.5 on 2023-01-21 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 21, 22, 30, 28, 551089, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
